import { useMemo, useState } from 'react';
import { Alert, Button, Descriptions, Drawer, Form, Grid, Input, InputNumber, Message, Modal, Select, Space, Tag, Typography } from '@arco-design/web-react';
import { IconPlus } from '@arco-design/web-react/icon';
import PageHeader from '../../components/PageHeader';
import FilterBar from '../../components/FilterBar';
import ResourceTable from '../../components/ResourceTable';
import StatusTag from '../../components/StatusTag';
import MessagePreview from '../../components/MessagePreview';
import type { SystemEventDefinition } from '../../domain/types';
import { registerSystemEvent, testSystemEvent, usePrototypeStore } from '../../store/prototypeStore';

export default function EventListPage(){
  const store=usePrototypeStore();const [keyword,setKeyword]=useState('');const [line,setLine]=useState<string>();const [status,setStatus]=useState<string>();const [selected,setSelected]=useState<SystemEventDefinition>();const [creating,setCreating]=useState(false);const [form]=Form.useForm();
  const data=useMemo(()=>store.events.filter((event)=>`${event.id}${event.name}`.toLowerCase().includes(keyword.toLowerCase())&&(!line||event.line===line)&&(!status||event.status===status)),[store.events,keyword,line,status]);
  const template=selected?store.templates.find((item)=>item.id===selected.templateId||`${item.code} ${item.version}`===selected.template):undefined;
  const register=async()=>{try{const values=await form.validate();registerSystemEvent({id:values.id,name:values.name,line:values.line,version:values.version,template:values.template,templateId:store.templates.find((item)=>`${item.code} ${item.version}`===values.template)?.id,caller:values.caller,variables:values.variables.split(',').map((item:string)=>item.trim()).filter(Boolean)});Message.success('事件已注册并进入待联调状态');setCreating(false);}catch{/* form */}};
  return <section className="page-stack"><PageHeader title="系统事件" description="管理八类核心事件的模板绑定、变量映射、测试发送与调用质量。" actions={<Button type="primary" icon={<IconPlus/>} onClick={()=>setCreating(true)}>注册事件</Button>}/><FilterBar onReset={()=>{setKeyword('');setLine(undefined);setStatus(undefined);}}><Input.Search value={keyword} onChange={setKeyword} placeholder="搜索事件编码或名称" style={{width:280}}/><Select placeholder="业务线" value={line} onChange={setLine} allowClear style={{width:140}} options={['资产','交易','风控','奖励'].map((value)=>({label:value,value}))}/><Select placeholder="调用状态" value={status} onChange={setStatus} allowClear style={{width:140}} options={['运行正常','轻微延迟','待联调'].map((value)=>({label:value,value}))}/></FilterBar><ResourceTable data={data} rowKey="id" columns={[{title:'事件',width:280,render:(_,record)=><div><Typography.Text className="strong">{record.name}</Typography.Text><div className="mono muted">{record.id}</div></div>},{title:'业务线',dataIndex:'line',width:90},{title:'版本',dataIndex:'version',width:90},{title:'绑定模板',dataIndex:'template',width:190},{title:'调用方',dataIndex:'caller',width:170,render:(value)=><Tag>{value}</Tag>},{title:'近24h调用',dataIndex:'calls',width:110},{title:'失败率',dataIndex:'failure',width:90},{title:'最后调用',dataIndex:'last',width:120},{title:'状态',width:110,render:(_,record)=><StatusTag status={record.status}/>},{title:'操作',fixed:'right',width:80,render:(_,record)=><Button type="text" onClick={()=>setSelected(record)}>详情</Button>}]}/>
    <Drawer width={900} visible={Boolean(selected)} title={selected?`事件详情 · ${selected.name}`:'事件详情'} onCancel={()=>setSelected(undefined)} footer={selected&&<Space><Button onClick={()=>Message.info('已生成事件 Schema 与变量映射检查报告')}>校验 Schema</Button><Button type="primary" onClick={()=>{testSystemEvent(selected.id);Message.success('测试事件已发送到 FCM Sandbox，并生成发送记录');}}>发送测试事件</Button></Space>}>{selected&&<><Descriptions column={3} border data={[{label:'事件编码',value:selected.id},{label:'版本',value:selected.version},{label:'调用方',value:selected.caller},{label:'绑定模板',value:selected.template},{label:'变量数量',value:selected.variables.length},{label:'最近测试',value:selected.lastTestAt||'尚未测试'}]}/><Alert style={{margin:'16px 0'}} type="info" title="变量映射" content={selected.variables.map((value)=>`{{ ${value} }}`).join(' · ')}/>{template?.content?<MessagePreview content={template.content}/>:<Alert type="warning" content="当前绑定模板为历史版本；请在模板中心发布新版本后重新绑定以查看双端预览。"/>}</>}</Drawer>
    <Modal visible={creating} title="注册业务事件" onCancel={()=>setCreating(false)} onOk={register} okText="注册并待联调" style={{width:780}} unmountOnExit><Form form={form} layout="vertical" initialValues={{version:'1.0.0',line:'资产',variables:'user_nickname, amount, currency, symbol, occurred_at'}}><Grid.Row gutter={16}><Grid.Col span={12}><Form.Item label="事件编码" field="id" required rules={[{required:true}]}><Input placeholder="deposit.credited"/></Form.Item></Grid.Col><Grid.Col span={12}><Form.Item label="事件名称" field="name" required rules={[{required:true}]}><Input/></Form.Item></Grid.Col><Grid.Col span={8}><Form.Item label="业务线" field="line"><Select options={['资产','交易','风控','奖励'].map((value)=>({label:value,value}))}/></Form.Item></Grid.Col><Grid.Col span={8}><Form.Item label="事件版本" field="version"><Input/></Form.Item></Grid.Col><Grid.Col span={8}><Form.Item label="事件 TTL"><InputNumber defaultValue={300} suffix="秒"/></Form.Item></Grid.Col></Grid.Row><Form.Item label="调用方" field="caller" required><Input/></Form.Item><Form.Item label="绑定已发布模板" field="template" required><Select options={store.templates.filter((item)=>item.translationReadiness==='全部审核通过').map((item)=>({label:`${item.name} · ${item.version}`,value:`${item.code} ${item.version}`}))}/></Form.Item><Form.Item label="变量映射" field="variables" extra="逗号分隔；测试事件会校验缺失与类型"><Input/></Form.Item></Form></Modal>
  </section>;
}
