import { useMemo, useState } from 'react';
import { Button, Card, Grid, Message, Progress, Select, Statistic, Tag } from '@arco-design/web-react';
import { IconDownload } from '@arco-design/web-react/icon';
import PageHeader from '../../components/PageHeader';
import FilterBar from '../../components/FilterBar';
import { usePrototypeStore } from '../../store/prototypeStore';

const categories=[['系统公告',82.4,420],['交易通知',72.8,1280],['资产通知',91.6,860],['安全通知',94.2,310],['奖励通知',67.5,580],['活动通知',48.9,920],['风控通知',96.8,190]];

export default function AnalyticsPage(){
  const store=usePrototypeStore();const [range,setRange]=useState('近7天');const [category,setCategory]=useState<string>();const [source,setSource]=useState<string>();const [risk,setRisk]=useState<string>();const [audience,setAudience]=useState<string>();const [locale,setLocale]=useState<string>();const [client,setClient]=useState('all');
  const records=useMemo(()=>store.deliveries.filter((record)=>(client==='all'||(client==='Web'&&record.channel==='站内信')||(client==='App'&&record.channel==='Push'))&&(!category||record.category===category)&&(!risk||record.risk===risk)),[store.deliveries,client,category,risk]);
  const metrics=(channel:'站内信'|'Push')=>{const rows=records.filter((item)=>item.channel===channel);const sent=rows.length;const delivered=rows.filter((item)=>['已送达','已打开','已点击'].includes(item.status)).length;const failed=rows.filter((item)=>Boolean(item.error)).length;const clicked=rows.filter((item)=>item.status==='已点击'||item.clickedAt).length;const retries=rows.reduce((sum,item)=>sum+item.retryCount,0);return{sent,deliveryRate:sent?delivered/sent*100:0,failureRate:sent?failed/sent*100:0,clickRate:sent?clicked/sent*100:0,retries,cost:channel==='Push'?'¥0（APNs/FCM）':'¥0（内部服务）'};};
  const web=metrics('站内信');const push=metrics('Push');
  const reset=()=>{setRange('近7天');setCategory(undefined);setSource(undefined);setRisk(undefined);setAudience(undefined);setLocale(undefined);setClient('all');};
  return <section className="page-stack"><PageHeader title="数据分析" description="对比 Web 站内信与 App Push 的发送、送达、失败、重试、阅读、点击和成本。" actions={<Button icon={<IconDownload/>} onClick={()=>Message.success(`已按当前筛选创建 ${records.length} 条记录的分析报表`)}>导出报表</Button>}/><FilterBar onReset={reset}><Select value={range} onChange={setRange} style={{width:120}} options={['近7天','近30天'].map((value)=>({label:value,value}))}/><Select placeholder="消息分类" value={category} onChange={setCategory} allowClear style={{width:140}} options={categories.map(([value])=>({label:value,value}))}/><Select placeholder="消息来源" value={source} onChange={setSource} allowClear style={{width:140}} options={[{label:'系统事件',value:'event'},{label:'人工发送',value:'manual'}]}/><Select placeholder="风险等级" value={risk} onChange={setRisk} allowClear style={{width:130}} options={['普通','重要','紧急'].map((value)=>({label:value,value}))}/><Select placeholder="受众类型" value={audience} onChange={setAudience} allowClear style={{width:140}} options={['全部用户','指定用户','指定 VIP','指定代理','活动参与用户'].map((value)=>({label:value,value}))}/><Select placeholder="语言" value={locale} onChange={setLocale} allowClear style={{width:120}} options={['zh-CN','en-US','ja-JP','tr-TR'].map((value)=>({label:value,value}))}/><Select value={client} onChange={setClient} style={{width:140}} options={[{label:'全部客户端',value:'all'},{label:'Web 站内信',value:'Web'},{label:'App Push',value:'App'}]}/><Tag color="purple">App Push</Tag></FilterBar>
    <div className="analytics-kpis v2-kpis">{[['生成消息数',`${Math.max(records.length,1)*3.3}M`,'当前筛选'],['触达用户数',`${Math.max(records.length,1)*3.1}M`,'去重 UID'],['阅读率','34.26%','+2.1pp'],['点击率','8.87%','+0.6pp'],['过期未读','18,420','-12.4%']].map(([title,value,note])=><Card key={title} bordered={false}><Statistic title={title} value={value}/><span className="kpi-note">{note}</span></Card>)}</div>
    <Grid.Row gutter={[16,16]}><Grid.Col span={12}><Card bordered={false} className="surface channel-metric-card" title="Web 站内信" extra={<Tag color="arcoblue">内部服务</Tag>}><div className="channel-metric-grid">{[['发送数',web.sent],['送达率',`${web.deliveryRate.toFixed(1)}%`],['失败率',`${web.failureRate.toFixed(1)}%`],['阅读率','38.6%'],['点击率',`${web.clickRate.toFixed(1)}%`],['重试次数',web.retries],['渠道成本',web.cost]].map(([label,value])=><div key={label as string}><span>{label}</span><strong>{value}</strong></div>)}</div></Card></Grid.Col><Grid.Col span={12}><Card bordered={false} className="surface channel-metric-card" title="App Push" extra={<Tag color="purple">APNs / FCM</Tag>}><div className="channel-metric-grid">{[['发送数',push.sent],['送达率',`${push.deliveryRate.toFixed(1)}%`],['失败率',`${push.failureRate.toFixed(1)}%`],['点击率',`${push.clickRate.toFixed(1)}%`],['重试次数',push.retries],['失效 Token',records.filter((item)=>item.tokenStatus==='已失效').length],['渠道成本',push.cost]].map(([label,value])=><div key={label as string}><span>{label}</span><strong>{value}</strong></div>)}</div></Card></Grid.Col></Grid.Row>
    <Grid.Row gutter={[16,16]}><Grid.Col xs={24} lg={15}><Card bordered={false} className="surface" title="阅读与点击趋势" extra={<Tag>数据延迟 8 分钟</Tag>}><div className="reading-trend">{[['07-07',42,12],['07-08',55,18],['07-09',48,15],['07-10',68,24],['07-11',62,20],['07-12',78,29],['07-13',72,26]].map(([day,read,click])=><div key={day as string}><div className="trend-bars"><i style={{height:`${read}%`}}/><b style={{height:`${click}%`}}/></div><span>{day}</span></div>)}</div><div className="trend-legend"><span><i/>阅读用户</span><span><b/>点击用户</span></div></Card></Grid.Col><Grid.Col xs={24} lg={9}><Card bordered={false} className="surface risk-metric-card" title="风险消息阅读时效" extra={<Tag color="red">紧急</Tag>}><div className="risk-read-metric"><span>5 分钟阅读率</span><strong>72.8%</strong><Progress percent={72.8} status="warning" showText={false}/></div><div className="risk-read-metric"><span>30 分钟阅读率</span><strong>94.6%</strong><Progress percent={94.6} status="success" showText={false}/></div><div className="risk-unread-alert"><span>过期仍未读</span><strong>286</strong><small>强平 42 · 提现风险 86 · 账户异常 158</small></div></Card></Grid.Col></Grid.Row>
    <Grid.Row gutter={[16,16]}><Grid.Col xs={24} lg={16}><Card bordered={false} className="surface" title="分类表现"><div className="category-performance"><div className="category-head"><span>消息分类</span><span>消息量</span><span>阅读率</span><span>表现</span></div>{categories.filter(([name])=>!category||name===category).map(([name,rate,count])=><div key={name as string}><strong>{name}</strong><span>{count}K</span><span>{rate}%</span><Progress percent={rate as number} size="small" showText={false} status={(rate as number)>90?'success':'normal'}/></div>)}</div></Card></Grid.Col><Grid.Col xs={24} lg={8}><Card bordered={false} className="surface" title="失败原因与重试"><div className="source-comparison"><div><span>临时失败</span><strong>{records.filter((item)=>item.retryable).length}</strong><small>允许指数退避重试</small></div><div><span>永久失败</span><strong>{records.filter((item)=>item.error&&!item.retryable).length}</strong><small>Token 失效或配置错误</small></div></div></Card></Grid.Col></Grid.Row>
  </section>;
}
