import { Alert, Button, Card, Grid, Progress, Select, Space, Table, Tag, Timeline, Typography } from '@arco-design/web-react';
import { IconCalendar, IconCheckCircle, IconClockCircle, IconExclamationCircle, IconNotification, IconSend } from '@arco-design/web-react/icon';
import PageHeader from '../../components/PageHeader';
import MetricCard from '../../components/MetricCard';
import StatusTag from '../../components/StatusTag';
import { openPrototypeDialog } from '../../utils/prototypeActions';
import { usePrototypeStore } from '../../store/prototypeStore';

const {Row,Col}=Grid;
const trendDays=[{label:'07/07',height:58,shares:[62,38]},{label:'07/08',height:72,shares:[59,41]},{label:'07/09',height:66,shares:[61,39]},{label:'07/10',height:84,shares:[56,44]},{label:'07/11',height:75,shares:[58,42]},{label:'07/12',height:92,shares:[54,46]},{label:'07/13',height:88,shares:[52,48]}];
const trendChannels=[{name:'站内信',className:'channel-inbox'},{name:'Push',className:'channel-push'}];

export default function DashboardPage(){
  const {tasks}=usePrototypeStore();
  return <section className="page-stack"><PageHeader title="消息运营工作台" description="监控 Web 站内信、App Push、审核队列与风险消息阅读时效。" actions={<><Select defaultValue="今日" style={{width:110}} options={['今日','近7天'].map((value)=>({label:value,value}))}/><Button icon={<IconCalendar/>} onClick={()=>openPrototypeDialog('选择统计日期','当前报表时区为 UTC+8，可切换自然日或自定义日期范围。')}>2026-07-13 · UTC+8</Button></>}/><Alert type="warning" showIcon content="APNs 无效 Token 比例升至 0.18%，已自动进入失效清理队列；FCM 与 Web 站内信运行正常。" action={<Button size="small" onClick={()=>openPrototypeDialog('Push 渠道告警','过去 30 分钟检测到 286 个永久失败回执，已停止重试并清理 Token。')}>查看告警</Button>}/><Row gutter={[16,16]}><Col xs={24} sm={12} lg={6}><MetricCard title="今日发送" value="12.84M" change="8.2%" icon={<IconSend/>}/></Col><Col xs={24} sm={12} lg={6}><MetricCard title="送达率" value="99.42" suffix="%" change="0.18%" icon={<IconCheckCircle/>}/></Col><Col xs={24} sm={12} lg={6}><MetricCard title="待审核" value={12} change="3 项新增" positive={false} icon={<IconClockCircle/>}/></Col><Col xs={24} sm={12} lg={6}><MetricCard title="风险消息未读" value="286" change="-12.4%" icon={<IconNotification/>}/></Col></Row>
    <div className="dashboard-grid"><Card className="surface chart-card" title="发送趋势" extra={<Space><Tag color="arcoblue">站内信</Tag><Tag color="purple">Push</Tag></Space>} bordered={false}><div className="bar-chart" role="img" aria-label="近 7 日发送趋势，按站内信和 Push 堆叠展示">{trendDays.map((day)=><div className="bar-group" key={day.label}><div className="bar-stack" style={{height:`${day.height}%`}}>{trendChannels.map((channel,index)=><span className={`bar-segment ${channel.className}`} style={{height:`${day.shares[index]}%`}} aria-label={`${day.label} ${channel.name}占比 ${day.shares[index]}%`} key={channel.name}/>)}</div><span>{day.label}</span></div>)}</div></Card><Card className="surface" title="渠道健康" bordered={false}>{[['站内信','99.999%',100,'正常'],['Push · APNs / FCM','99.82%',98,'正常']].map(([name,rate,percent,status])=><div className="health-row" key={name as string}><div><strong>{name}</strong><span>{rate} 成功</span></div><Progress percent={percent as number} size="small" showText={false} status={status==='正常'?'success':'warning'}/><StatusTag status="运行正常"/></div>)}</Card></div>
    <div className="dashboard-grid wide-left"><Card className="surface" title="进行中的关键任务" bordered={false}><Table pagination={false} rowKey="id" data={tasks.slice(0,5)} columns={[{title:'任务',dataIndex:'name'},{title:'渠道',render:(_,record)=>record.channels.join(' + ')},{title:'目标用户',render:(_,record)=>record.audienceCount.toLocaleString()},{title:'状态',render:(_,record)=><StatusTag status={record.status}/>},{title:'成功率',render:(_,record)=>record.successRate?`${record.successRate}%`:'—'}]}/></Card><Card className="surface" title="实时动态" bordered={false}><Timeline pending="持续监控中">{['18:03 提现通知完成第 12 个分片','18:02 APNs 无效 Token 清理任务启动','17:58 夏季交易赛模板通过内容审核','17:44 风控规则 POL-EU-07 发布'].map((item,index)=><Timeline.Item key={item} dot={index===1?<IconExclamationCircle style={{color:'#f79009'}}/>:undefined}><Typography.Text>{item}</Typography.Text></Timeline.Item>)}</Timeline></Card></div>
  </section>;
}
