import { useMemo, useState } from 'react';
import { Alert, Button, DatePicker, Descriptions, Drawer, Input, Message, Modal, Select, Space, Tabs, Tag, Typography } from '@arco-design/web-react';
import { IconDownload, IconRefresh } from '@arco-design/web-react/icon';
import type { TableColumnProps } from '@arco-design/web-react';
import PageHeader from '../../components/PageHeader';
import FilterBar from '../../components/FilterBar';
import ResourceTable from '../../components/ResourceTable';
import StatusTag from '../../components/StatusTag';
import type { DeliveryRecord } from '../../domain/types';
import { retryDelivery, suppressDeliveryToken, usePrototypeStore } from '../../store/prototypeStore';
import WritePermissionButton from '../../components/WritePermissionButton';
import { useCurrentPagePermission } from '../../components/PagePermissionBoundary';

export default function DeliveryPage(){
  const {canWrite}=useCurrentPagePermission();
  const store=usePrototypeStore();const [selected,setSelected]=useState<DeliveryRecord>();const [tab,setTab]=useState('all');const [keyword,setKeyword]=useState('');const [channel,setChannel]=useState<string>();const [status,setStatus]=useState<string>();const [category,setCategory]=useState<string>();const [risk,setRisk]=useState<string>();const [eventCode,setEventCode]=useState<string>();
  const data=useMemo(()=>store.deliveries.filter((record)=>{const hit=`${record.id}${record.task}${record.user}${record.eventCode||''}`.toLowerCase().includes(keyword.toLowerCase());const tabHit=tab==='all'||(tab==='push'&&record.channel==='Push')||(tab==='inbox'&&record.channel==='站内信')||(tab==='failures'&&Boolean(record.error));return hit&&tabHit&&(!channel||record.channel===channel)&&(!status||record.status===status)&&(!category||record.category===category)&&(!risk||record.risk===risk)&&(!eventCode||record.eventCode===eventCode);}),[store.deliveries,tab,keyword,channel,status,category,risk,eventCode]);
  const columns:TableColumnProps<DeliveryRecord>[]=[{title:'发送实例',width:210,render:(_,record)=><div><span className="mono">{record.id}</span><div className="muted">{record.task}</div><small className="mono">{record.eventCode}</small></div>},{title:'关联触发',width:170,render:(_,record)=>record.triggerId?<span className="mono">{record.triggerId}</span>:<span className="muted">人工任务</span>},{title:'用户',dataIndex:'user',width:130},{title:'目标地址',dataIndex:'destination',width:160,render:(value)=><span className="mono">{value}</span>},{title:'渠道 / 平台',width:140,render:(_,record)=><div><Tag color={record.channel==='Push'?'purple':'arcoblue'}>{record.channel}</Tag><div className="muted">{record.devicePlatform||record.provider}</div></div>},{title:'状态',width:120,render:(_,record)=><StatusTag status={record.status}/>},{title:'提交 / 送达',width:190,render:(_,record)=><div>{record.submittedAt}<div className="muted">{record.deliveredAt}</div></div>},{title:'错误码',width:150,render:(_,record)=><span className={record.error?'error-copy':'muted'}>{record.errorCode||'—'}</span>},{title:'重试',dataIndex:'retryCount',width:70},{title:'费用',dataIndex:'cost',width:90},{title:'操作',fixed:'right',width:80,render:(_,record)=><Button type="text" onClick={()=>setSelected(record)}>详情</Button>}];
  const reset=()=>{setKeyword('');setChannel(undefined);setStatus(undefined);setCategory(undefined);setRisk(undefined);setEventCode(undefined);};
  const retry=()=>{if(!canWrite){Message.warning('当前账号无写权限');return;}if(!selected)return;retryDelivery(selected.id);setSelected(undefined);Message.success('临时失败实例已进入指数退避重试队列');};
  return <section className="page-stack"><PageHeader title="渠道发送记录" description="按人工任务或事件触发记录追踪每一个站内信（Web + App）和 App Push 渠道实例。" actions={<><WritePermissionButton icon={<IconRefresh/>} onClick={()=>Message.success('已刷新 APNs / FCM 与站内信回执')}>刷新回执</WritePermissionButton><Button icon={<IconDownload/>} onClick={()=>Modal.confirm({title:'申请脱敏导出',content:`将按当前筛选导出 ${data.length} 条记录；明文 PII 需单独审批。`,onOk:()=>{Message.success('导出任务已创建');}})}>申请导出</Button></>}/><Alert type="info" content="站内信在 Web 与 App 共用消息实例及已读状态；目标地址默认脱敏，查看完整 Token、UID 或供应商原始回执需要 PII 权限并记录审计日志。"/>
    <Space><Button status="danger" onClick={()=>setSelected(store.deliveries.find((item)=>item.error))}>查看失败原因</Button></Space>
    <Tabs activeTab={tab} onChange={setTab}><Tabs.TabPane key="all" title={`全部记录 (${store.deliveries.length})`}/><Tabs.TabPane key="inbox" title="站内信"/><Tabs.TabPane key="push" title="App Push"/><Tabs.TabPane key="failures" title={`失败记录 (${store.deliveries.filter((item)=>item.error).length})`}/></Tabs>
    <FilterBar onReset={reset}><Input.Search value={keyword} onChange={setKeyword} placeholder="实例 ID、任务、事件或 UID" style={{width:250}}/><Select placeholder="渠道" value={channel} onChange={setChannel} allowClear style={{width:130}} options={['站内信','Push'].map((value)=>({label:value,value}))}/><Select placeholder="状态" value={status} onChange={setStatus} allowClear style={{width:140}} options={['已送达','已点击','临时失败','永久失败','重试中','已抑制'].map((value)=>({label:value,value}))}/><Select placeholder="消息分类" value={category} onChange={setCategory} allowClear style={{width:140}} options={['系统公告','交易通知','资产通知','安全通知','奖励通知','活动通知','风控通知'].map((value)=>({label:value,value}))}/><Select placeholder="风险等级" value={risk} onChange={setRisk} allowClear style={{width:120}} options={['普通','重要','紧急'].map((value)=>({label:value,value}))}/><Select placeholder="事件编码" value={eventCode} onChange={setEventCode} allowClear showSearch style={{width:190}} options={store.events.map((event)=>({label:event.id,value:event.id}))}/><DatePicker.RangePicker showTime style={{width:310}}/></FilterBar>
    <ResourceTable data={data} columns={columns} rowKey="id"/>
    <Drawer width={720} visible={Boolean(selected)} title={selected?`${selected.id} · 发送详情`:'发送详情'} onCancel={()=>setSelected(undefined)} footer={selected?.error?<Space><WritePermissionButton onClick={()=>{suppressDeliveryToken(selected.id);setSelected(undefined);Message.success('目标已加入抑制名单并记录审计');}}>加入抑制名单</WritePermissionButton><WritePermissionButton type="primary" disabled={!selected.retryable} onClick={retry}>立即重试</WritePermissionButton></Space>:null}>{selected&&<><Descriptions column={2} border data={[{label:'来源',value:selected.triggerId?'事件触发':'人工任务'},{label:'关联触发',value:selected.triggerId||'—'},{label:'任务 / 规则',value:selected.task},{label:'事件编码',value:selected.eventCode||'人工发送'},{label:'UID',value:selected.user},{label:'分类 / 风险',value:`${selected.category} · ${selected.risk}`},{label:'渠道 / 平台',value:`${selected.channel} · ${selected.devicePlatform||'Web'}`},{label:selected.channel==='站内信'?'阅读来源':'供应商',value:selected.channel==='站内信'?(selected.devicePlatform||'尚未阅读'):selected.provider},{label:selected.channel==='站内信'?'跨端同步':'目标',value:selected.channel==='站内信'?'Web / App 已同步':selected.destination},{label:'Token 状态',value:selected.tokenStatus},{label:'供应商消息 ID',value:selected.providerMessageId},{label:'状态',value:<StatusTag status={selected.status}/>},{label:'提交时间',value:selected.submittedAt},{label:'送达时间',value:selected.deliveredAt},{label:'点击时间',value:selected.clickedAt||'—'},{label:'重试次数',value:selected.retryCount},{label:'错误码',value:selected.errorCode||'—'},{label:'费用',value:selected.cost}]}/>{selected.error&&<Alert style={{marginTop:20}} type="error" title="标准失败原因" content={`${selected.error} · ${selected.retryable?'临时错误允许退避重试':'永久错误禁止重试'}`}/>}<div className="receipt-block"><Typography.Text bold>回执时间线</Typography.Text><p>{selected.submittedAt} · 提交 {selected.provider}</p><p>{selected.deliveredAt} · {selected.status}</p>{selected.retryCount>0&&<p>指数退避重试 #{selected.retryCount}</p>}{selected.clickedAt&&<p>{selected.clickedAt} · 用户点击并打开 Deep Link</p>}</div></>}</Drawer>
  </section>;
}
